<link href="<%=basePath%>resources/sui-mobile/dist/css/sm.css" rel="stylesheet" />
<link href="<%=basePath%>resources/sui-mobile/dist/css/sm-extend.min.css" rel="stylesheet" />
<link href="<%=basePath%>resources/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
<link href="<%=basePath%>resources/css/basic.css" rel="stylesheet" />

<link href="<%=basePath%>resources/icheck/css/icheck.css" rel="stylesheet" />

<script src="<%=basePath%>resources/js/zepto/zepto.js" type="text/javascript"></script>

<script src="<%=basePath%>resources/icheck/js/zepto.icheck.js" type="text/javascript"></script>


<script src="<%=basePath %>resources/js/plugin/iscroll.js"  type="text/javascript" ></script>
<script src="<%=basePath %>resources/js/plugin/iscroll-probe.js" type="text/javascript" ></script>
<script src="<%=basePath%>resources/js/plugin/zepto.fx_methods.js" type="text/javascript" ></script>
<script src="<%=basePath %>resources/swiper/dist/js/swiper.min.js" type="text/javascript" ></script>
<script src="<%=basePath%>resources/js/plugin/zepto.ajax.js" type="text/javascript"></script>
<script src="<%=basePath%>resources/js/plugin/zepto.getParam.js" type="text/javascript"></script>
<script src="<%=basePath%>resources/js/plugin/zepto.verification.js" type="text/javascript"></script>
<script src="<%=basePath%>resources/js/plugin/zepto.getScript.js" type="text/javascript"></script>
<script src="<%=basePath%>resources/js/plugin/zepto.lazyload.js" type="text/javascript"></script>

<script src="<%=basePath%>resources/js/util/util.forward.js" type="text/javascript"></script>
<script src="<%=basePath%>resources/js/util/util.date.js" type="text/javascript"></script>
<script src="<%=basePath%>resources/js/util/util.uuid.js" type="text/javascript"></script>



